const DEFAULT_CATEGORY = [
    { icon: 'school', name: 'Education', color: '#1abc9c' },
    { icon: 'directions_bus', name: 'Transportation', color: '#2ecc71' },
    { icon: 'exercise', name: 'Workout', color: '#3498db' },
    { icon: 'family_restroom', name: 'Family', color: '#9b59b6' },
    { icon: 'lunch_dining', name: 'Food', color: '#f1c40f' },
    { icon: 'local_cafe', name: 'Coffee', color: '#e67e22' },
    { icon: 'redeem', name: 'Gifts', color: '#e74c3c' },
    { icon: 'house', name: 'Home', color: '#f368e0' },
    { icon: 'health_and_safety', name: 'Health', color: '#ff9f43' },
    { icon: 'account_balance_wallet', name: 'Leisure', color: '#341f97' },
    { icon: 'pets', name: 'Pets', color: '#2e86de' },
    { icon: 'help', name: 'Other', color: '#576574' }
];

const CATEGORIES = [
    { icon: 'school' },
    { icon: 'directions_bus' },
    { icon: 'exercise' },
    { icon: 'family_restroom' },
    { icon: 'lunch_dining' },
    { icon: 'local_cafe' },
    { icon: 'redeem' },
    { icon: 'house' },
    { icon: 'health_and_safety' },
    { icon: 'account_balance_wallet' },
    { icon: 'pets' },
    { icon: 'help' },
    { icon: 'account_balance' },
    { icon: 'volunteer_activism' },
    { icon: 'calculate' },
    { icon: 'payments' },
    { icon: 'monetization_on' },
    { icon: 'euro' },
    { icon: 'currency_exchange' },
    { icon: 'bar_chart' },
    { icon: 'money' },
    { icon: 'local_shipping' },
    { icon: 'train' },
    { icon: 'directions_boat' },
    { icon: 'local_gas_station' },
    { icon: 'pedal_bike' },
    { icon: 'two_wheeler' },
    { icon: 'tram' },
    { icon: 'local_parking' },
    { icon: 'flight' },
    { icon: 'shopping_cart' },
    { icon: 'photo_camera' },
    { icon: 'sports_esports' },
    { icon: 'package' },
    { icon: 'dresser' },
    { icon: 'smartphone' },
    { icon: 'laptop_mac' },
    { icon: 'watch' },
    { icon: 'dishwasher_gen' },
    { icon: 'sports_bar' },
    { icon: 'local_pizza' },
    { icon: 'ramen_dining' },
    { icon: 'local_bar' },
    { icon: 'icecream' },
    { icon: 'nutrition' },
    { icon: 'sports_basketball' },
    { icon: 'sports_soccer' },
    { icon: 'sports_baseball' },
    { icon: 'sports_football' },
    { icon: 'sports_rugby' },
    { icon: 'sports_golf' }
];

module.exports = {
    DEFAULT_CATEGORY,
    CATEGORIES
}